[package]
name = "qsc_project"

authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true


[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
miette = { workspace = true }
regex-lite = { workspace = true }
async-trait = { workspace = true }
qsc_linter = { path = "../qsc_linter" }
qsc_data_structures = { path = "../qsc_data_structures" }
rustc-hash = { workspace = true }
futures = { workspace = true }
log = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }
qsc_project = { path = ".", features = ["fs"] }

[features]
fs = []

[lints]
workspace = true

[lib]
doctest = false
